master-data:
  bank-accounts:
  - 4002-778881-000
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - May25.
  - EidBonus-May25
  - Jun25.
  - Jul25.
  - Aug25.
  - Sep25.
  - Oct25.
  - Nov25.
  - Dec25.
selection:
  selected-account: 4002-778881-000
  selected-mode: Cheque
  selected-month: Aug25.
  selected-reference: 25/72
