master-data:
  bank-accounts:
  - 2219135014087
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - Dec25.
  - Jan26.
  - EidBonus-Feb26
  - Feb26.
  - Mar26.
  - EidBonus-Apr26
  - Apr26.
  - May26.
  - Jun26.
  - Jul26.
  - Aug26.
  - Sep26.
  - Oct26.
  - Nov26.
  - Dec26.
selection:
  selected-account: '2219135014087'
  selected-mode: Cheque
  selected-month: Dec25.
  selected-reference: 25/78
